### ISSUE TITLE
commitFileFailed

### ISSUE THREAD

**Issue by BladeFireLight** [tabs-not-spaces/Intune-App-Deploy#1]
I tried publishing the sample app to my tenant and got this error

Aborting with exception: System.Management.Automation.RuntimeException: File upload state is not success: commitFileFailed

above that I see 
WARNING: The term 'C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy\AzCopy.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.

And inn Intune > client apps : the SampleApp exists, but states "Your app is not ready yet. Check back again soon."

Is it possible I'm missing a prerequisite?

**Comment by tabs-not-spaces** [comment]
It is indeed possible and 100% the reason you ran into that error.

I tweaked the code base to use azcopy to handle the transfer of the media to Intune, but haven't included code to prep the pre-req.

Ideally all that is required is to download the azcopy binary and place it *somewhere* and remove the hard coded location of the tool.

I'll make the change in a few hours, but if someone is looking for a nice easy contribution, this wouldn't take longer than a few minutes of work!

**Comment by BladeFireLight** [comment]
I did install azcopy. it did not resolve the error. and I have yet to get the test package to install.

trying to create a package that downloads a zip and extracts did not go well either. it extracts all the zip files directly into bin but then expects them to be in a sub folder of bin. 

It also errors out if I do not clean up the folders between runs. quite frustrating in test but probably would not be an issue in a pipeline. 

If I can figure out a way to get things working I will do a PR. but first I need to understand why it does what it does. 

This project has some great potential and I want to help. I have a number of things that do not work with MSIX.

**Comment by tabs-not-spaces** [comment]
I can look at the zip extraction as another issue, but for now - can you review the recent changes and verify if you can upload a local package with the new pre-req for AzCopy and the updated commands for the latest version of AzCopy? - I'll re-open the issue and await your response.

**Comment by BladeFireLight** [comment]
No good. still dies the same place. 

it looks like the file was uploaded, just not commited. 


Uploading file to Azure Storage...
INFO: Scanning...

Job 65a465dd-a1be-a44c-4c96-fddc5d8fe281 has started
Log file is located at: C:\Users\dmjones\.azcopy\65a465dd-a1be-a44c-4c96-fddc5d8fe281.log

0.0 %, 0 Done, 0 Failed, 1 Pending, 0 Skipped, 1 Total,


Job 65a465dd-a1be-a44c-4c96-fddc5d8fe281 summary
Elapsed Time (Minutes): 0.0334
Total Number Of Transfers: 1
Number of Transfers Completed: 1
Number of Transfers Failed: 0
Number of Transfers Skipped: 0
TotalBytesTransferred: 1120
Final Job Status: Completed

File upload completed..

Committing the file into Azure Storage...
POST https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/34c236f2-802f-4f80-97bc-188485b31bfd/microsoft.graph.win32LobApp/contentVersions/1/files/a64ff752-0c49-4f19-8835-de60289a6d1a/commit
{
    "fileEncryptionInfo":  {
                               !!! removed !!!
                           }
}


Waiting for the service to process the commit file request...
GET https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/34c236f2-802f-4f80-97bc-188485b31bfd/microsoft.graph.win32LobApp/contentVersions/1/files/a64ff752-0c49-4f19-8835-de60289a6d1a
GET https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/34c236f2-802f-4f80-97bc-188485b31bfd/microsoft.graph.win32LobApp/contentVersions/1/files/a64ff752-0c49-4f19-8835-de60289a6d1a


Aborting with exception: System.Management.Automation.RuntimeException: File upload state is not success: commitFileFailed

**Comment by tabs-not-spaces** [comment]
If possible, can you provide me with the install media and app.yaml file being used (if different than just the sample app of course) - I'll try and replicate the issue in my end

**Comment by BladeFireLight** [comment]
This is just the sample one. 

Is there some pre-requisite to upload files via graph? 
I'm a Global Admin for the tenant, but do i need to register a provider?

**Comment by tabs-not-spaces** [comment]
It's just using the "well known" Intune aad application which if you hadn't already provided approval for then you wouldn't have been able to perform any of the other calls.

I'll spin up a fresh host and try and replicate the issue you are facing as soon as I get a chance. I'd suggest if you have the resources to do the same. 

Clean build of w10, nothing but vscode, git and direct access to the internet should be all that's required.

**Comment by BladeFireLight** [comment]
I do have the resources. I will get on that. 

I also opened a support ticket with Microsoft Premier Support in case this is something with my tenant.

**Comment by tabs-not-spaces** [comment]
managed to replicate the issue reported. the current theory is that the solution isn't happy with small application payloads. I just tried packaging 7zip as an example which is only ~1.6mb and i get the following:
![image](https://user-images.githubusercontent.com/33951277/69195846-f3aad500-0b80-11ea-8380-6ed5d0248d89.png)

If I follow the API call I can confirm that it has failed to "commit" the payload to intune:
![image](https://user-images.githubusercontent.com/33951277/69195927-29e85480-0b81-11ea-9381-2c04c6adf16d.png)

Now if I add in some junk files to increase the resultant *.intunewin package payload it succeeds. I'll need to spend more time investigating what is failing, but my current suspicion is azCopy is not playing nicely with the small files...

**Comment by BladeFireLight** [comment]
I turned on a bunch of loggin and noticed this descripency. 
This was in what was in the output. 
size                              : 1753
sizeEncrypted                     : 1808

Now size comes from the XML and it matches. 
size encrypted is supposed to come form the file length property.  and that is a different size.
(Get-Item .\SampleApp.intunewin).Length
3066

**Comment by BladeFireLight** [comment]
Never mind on that. I was looking at the wrapper file not install-app.intunewin.  those sizes do match.

**Comment by BladeFireLight** [comment]
it looks like the magic number is just over 9mb . I created a dummy file with completely random content so it would not compress at 9.1mb and it uploads.

**Comment by tabs-not-spaces** [comment]
Gives me somewhere to start looking!
I'll have a play and see what I come up with.

**Comment by BladeFireLight** [comment]
The dummy file I added has to be difficult to compress. so I used this. 

$bytes = 9.1MB

[System.Security.Cryptography.RNGCryptoServiceProvider] $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider

$rndbytes = New-Object byte[] $bytes

$rng.GetBytes($rndbytes)

[System.IO.File]::WriteAllBytes("C:\Git\Intune-App--eploy\applications\samplePowershell\dummy.dat", $rndbytes)

**Comment by tabs-not-spaces** [comment]
so we could potentially (until this is resolved) just place a dummy file into each package so that it completes correctly. not that I like the solution - but if it gets small apps over the line, I'd be happy.

if you have time, i'd suggest doing a check to see if the payload is smaller than 10mb before the build commences, and if so, run that block of code.

ideally bundle that dummy generator into a function and put it in the [build.functions.ps1](https://github.com/tabs-not-spaces/Intune-App-Deploy/tree/master/tasks/Build.Functions.ps1)

then call it from [invoke.build.ps1](https://github.com/tabs-not-spaces/Intune-App-Deploy/tree/master/tasks/Invoke.Build.ps1)

throw it into a PR and i'll review.

**Comment by BladeFireLight** [comment]
I was thinking the same thing.   it's a good stop-gap. 

Not sure on the detection piece as your code has some issues cleaning up that would effect the calculations.

**Comment by BladeFireLight** [comment]
Ok. I have a PR. I think all the bugs are out of it.

**Comment by tabs-not-spaces** [comment]
e8a6970e937a0adc996a92580a3114af4f0c896c should fix this issue. Let me know if the problem reoccurs.
