### ISSUE TITLE
Support for Executable Installers

### ISSUE THREAD

**Issue by devinmcelheran** [tabs-not-spaces/Intune-App-Deploy#6]
Hi,

I was reading through some of the code and I don't believe I saw support for non MSI installers. Would it be difficult implement this support? And would the YAML file have to be modified to accommodate a non MSI file?

I'm willing to try and help with this, but this project exceeds my current understanding of many of these matters.

**Comment by tabs-not-spaces** [comment]
There's support for anything you know how to install. As a rule, I wrap all
installers in a PowerShell script to aid in logging and error handling, but
as long as you know how to install it, you can with this solution.
